services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=macro_user
      - POSTGRES_PASSWORD=macro_pass
      - POSTGRES_DB=macro_econ
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://macro_user:macro_pass@postgres:5432/macro_econ
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: