services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=macro_user
      - POSTGRES_PASSWORD=macro_pass
      - POSTGRES_DB=macro_econ
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U macro_user -d macro_econ"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 可选：添加pgAdmin方便数据库管理
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: